language: python
python:
  - "2.7"
before_install:
  - gem install sass
install:
  - pip install -r requirements.txt
script:
  - python build.py test
notifications:
  slack: govlab:KLK7vzipwKmNg6927T5KPrjc
