language: python
python:
- '2.7'
before_install:
- gem install sass
install:
- pip install -r requirements.txt
script:
- python build.py test
notifications:
  slack:
    secure: mVVT6E9G0wzLSdKxl0H5cSCaMYfB2LAwA9F4hrYt2l4YthsP1Gp7qoCScxEKl/tzdr+v2sHE11T489zLZOnmkeVmcYyneCHUDdQo1KBufHHjROru5tRpNbe0K6/fxXdwBq5n3NWre9GsXPZNBl0qILTKZF5Rb3kBWJpswVQYWQ0MTmOlf1uCa85HPcGeruWP6WfqHiQoEHO0Et3BLrHvolo4kE5ewJyE5zIvNHSvSsmgxtRIbmW+3aItHEdDqn6/WVvZoA72tAAAbqVdL6qulll55en8J9PAbA3RmmRzFoT/ZXr1vAhHrtuNYS68vnk3yO24FX2jJPhg9AIie4X3iA+NAzj7Is3vA2JU0NjOX3GN/YaTwlnWJL/+qd/LcwmRqOgqGkmv0WXC6RpmZ9zlfc0neDFbc6VzpKAaH7jwrRkfbNMoVJvJanndI5bFKvo+Xs19n+nXfSfzXYsT9HirIz1kiet1RMvIAyAZFJpvfFITZBVpDr2PBj8aQ8gLC8a2Ngwg9dhb/412PiClmE/tDJeZtAl6E7XaZ2N34ecFiaO4pV7CK8Jirdgqe54q19Q8sDuFFS7BLH9mxuEOO5GdQX+7mR4gWrAqufUOkMqQ40UHVrRsNUmiBywACMBFfdUJGkbCEmtspm3FcgmSaCPg506rFOKHwPw/AAf075Qwp4s=
